[package]
name = "mdbx-sys"
version = "1.0.0"
authors = ["Usama Sarwar <usamasarwar@users.noreply.github.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/usamasarwar/isar_db"
description = "MDBX bindings for Isar DB"

[lib]
name = "mdbx_sys"
doctest = false

[build-dependencies]
cmake = "0.1"
cc = "1.0"
bindgen = { version = "0.71", default-features = false, features = ["runtime"] }
