[package]
name = "isar"
version = "1.0.0"
authors = ["Usama Sarwar <usamasarwar@users.noreply.github.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/usamasarwar/isar_db"
description = "Isar DB FFI - Foreign Function Interface for Isar Core"

[dependencies]
isar-core = { path = "../isar_core", default-features = false }
serde = "1.0"
serde_json = "1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[lib]
crate-type=["staticlib", "cdylib"]

[features]
default = ["sqlite", "native"]
native = ["isar-core/native"]
sqlite = ["isar-core/sqlite"]
sqlcipher = ["sqlite", "isar-core/sqlcipher"]
sqlcipher-vendored = ["sqlcipher", "isar-core/sqlcipher-vendored"]