name: isar_test
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  isar_db:
    path: ../isar_db
  intl: ^0.20.2
  json_annotation: ^4.9.0
  meta: ^1.16.0
  test: any

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.8.0
