name: isar_db_flutter_libs
description: Isar Core native binaries for the Isar Database (isar_db). Required dependency for Flutter apps using isar_db. Enhanced fork with Android 16KB page size support and improved web persistence.
version: 1.0.0
repository: https://github.com/usamasarwar/isar_db
homepage: https://github.com/usamasarwar/isar_db
issue_tracker: https://github.com/usamasarwar/isar_db/issues

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.isar.isar_db_flutter_libs
        pluginClass: IsarDbFlutterLibsPlugin
      ios:
        pluginClass: IsarDbFlutterLibsPlugin
      macos:
        pluginClass: IsarDbFlutterLibsPlugin
      linux:
        pluginClass: IsarDbFlutterLibsPlugin
      windows:
        pluginClass: IsarDbFlutterLibsPlugin
      web:
