[package]
name = "isar-wasm"
version = "1.0.0"
authors = ["Usama Sarwar <usamasarwar@users.noreply.github.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/usamasarwar/isar_db"
description = "Isar DB WASM - WebAssembly implementation for Isar database"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
# WASM-specific dependencies
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
  "console",
  "Window",
  "Navigator",
  "Document",
  "Element",
  "HtmlElement",
  "Storage",
  "IdbDatabase",
  "IdbOpenDbRequest",
  "IdbRequest",
  "IdbTransaction",
  "IdbTransactionMode",
  "IdbObjectStore",
  "IdbCursor",
  "IdbCursorDirection",
  "IdbKeyRange",
  "IdbIndex",
  "IdbFactory",
  "IdbVersionChangeEvent"
]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"

# WASM-compatible SQLite
sqlite-wasm-rs = "0.1"

# Core dependencies (shared with main package)
itertools = "0.14"
enum_dispatch = "0.3.13"
xxhash-rust = { version = "0.8.10", features = ["xxh3"] }
byteorder = "1"
intmap = "3.1"
snafu = "0.8"
ouroboros = "0.18"
base64 = "0.22"
paste = "1"
parking_lot = "0.12"
proc-macro2 = "1"
arc-swap = "1.7"

[features]
default = ["console_error_panic_hook"]

[dependencies.console_error_panic_hook]
version = "0.1"
optional = true

# web-sys features are already defined above
