[package]
name = "isar-core"
version = "1.0.0"
authors = ["Usama Sarwar <usamasarwar@users.noreply.github.com>"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/usamasarwar/isar_db"
description = "Isar DB Core - Fast, easy-to-use, fully async NoSQL database for Flutter"

[dependencies]
itertools = "0.14"
enum_dispatch = "0.3.13"
xxhash-rust = { version = "0.8.10", features = ["xxh3"] }
serde =  { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
byteorder = "1"
intmap = "3.1"
snafu = "0.8"
ouroboros = "0.18"
base64 = "0.22"
paste = "1"
parking_lot = "0.12"
proc-macro2 = "1"
arc-swap = "1.7"

libsqlite3-sys = { version = "0.35", features=["bundled"], optional = true  }
mdbx-sys = { package = "mdbx-sys", path = "../mdbx_sys", optional = true  }

# WASM-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"
sqlite-wasm-rs = { version = "0.1", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
widestring = "1.0"

[dev-dependencies]
cfg-if = "1"
float_next_after = "1"

[dev-dependencies.serde_json]
version = "*"
features = ["float_roundtrip"]

[features]
default = ["native", "sqlite"]
native = ["mdbx-sys"]
sqlite = ["libsqlite3-sys"]
sqlcipher = ["sqlite", "libsqlite3-sys/bundled-sqlcipher"]
sqlcipher-vendored = ["sqlcipher", "libsqlite3-sys/bundled-sqlcipher-vendored-openssl"]
wasm = ["sqlite-wasm-rs"]
# For WASM builds, use a different approach
[target.'cfg(target_arch = "wasm32")'.features]
default = ["wasm", "sqlite"]
