name: isar_db_test

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  intl: ^0.20.2
  isar_db:
    path: ../isar_db
  isar_db_flutter_libs:
    path: ../isar_db_flutter_libs
  isar_test:
    path: ../isar_test
  json_annotation: ^4.9.0
  meta: ^1.16.0
  path: ^1.9.0
  path_provider: ^2.1.4
  test: any

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

dependency_overrides:
  dart_style: ^3.0.1
  isar_db:
    path: ../isar_db
  isar_db_flutter_libs:
    path: ../isar_db_flutter_libs
