name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build Documentation
        run: |
          mkdir -p _site
          cp docs/*.md _site/ 2>/dev/null || true
          cp docs/README.md _site/index.md
          cp -r docs/recipes _site/ 2>/dev/null || true
          cp -r docs/tutorials _site/ 2>/dev/null || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
